### ISSUE TITLE
Android wallet not connecting/syncing

### ISSUE THREAD

**Issue by lucas-iao** [cannabiscoindev/cannabiscoin-android-wallet#1]
Does anyone know how to connect the android wallet to the network? I can not see my balance or use the wallet because it wont connect.. Thank you

**Comment by soulstar205** [comment]
Why is no one responding or proffering solutions to this problem.
I sent some CANNs to my wallet and nothing shows up, I Just might have lost $100, can someone help pls, its been four days now

**Comment by Bushstar** [comment]
This project does not seem to be active, I was commissioned to work on it in the past but there does not seem to be active monitoring of issues. As I still have the logins for the DNS seeders I did login and check them, they've run out of disk space. I deleted some log files to make room and have restarted the seeder services. My wallet can connect again and I will inform the owner of the coin that he needs new servers.

**Comment by soulstar205** [comment]
Hello, is there something I can do to get my coins delivered to my wallet?
Do i need to update or download something.
Pls respond

**Comment by Bushstar** [comment]
The Android wallet should not be able to connect to the network again. Open it up and check the Network Monitor to make sure that it is connected, if so wait and it will sync given time.

**Comment by soulstar205** [comment]
Hey Peter, I received a message you supposedly sent to the owners of CANN,
this is probably because I left a message as well. I bought some coins and
sent them to my android wallet but they never showed up, the wallet
connects to 1peer sometimes, and my coins haven't showed up yet. Can you
give me pointers as to what I can do to salvage this? Thanks

**Comment by PoUpA** [comment]
Hi, you'll have to wait till the chain is downloaded and it takes time.
In the wallet go to parameters> Trusted peer and try 100.34.73.160 or
seed.cannabiscoin.net
To see if your blocks are up to date go to network  and swipe to blocks.
You'll have the last downloaded block

**Comment by Bushstar** [comment]
I've made contact and have spoken to the owner this morning, he's going to build some more servers additional space. I'll also link them into this chat so they assist you.

As long as you have a connection you will sync with the network, it can take a while. Otherwise back up the wallet and extract the private key with the following OpenSSL command.

openssl enc -d -aes-256-cbc -a -in <filename>

**Comment by soulstar205** [comment]
thanks a lot for replying, I'll keep you posted as it goes.

**Comment by soulstar205** [comment]
So the blocks are up to date now, does the transaction download separately?
Balance is still empty.

**Comment by Bushstar** [comment]
Please post the address you sent the coins from the wallet and the TXID from where you made the withdrawal and I'll look the two up on the explorer to make sure that the coins have actually been sent and are confirmed.

**Comment by PoUpA** [comment]
maybe we can provide more help with the tx id or the sending address. Are
you sure this is the good wallet and good coin ?

**Comment by Bushstar** [comment]
Whatever happens do not uninstall the app as it will remove your private keys.

**Comment by soulstar205** [comment]
I sent the coin from an exchange site that I bought the coins from, that's
cryptopia.co.nz. I don't has the address.
This is mine:
CQEJrMPdLkUYGcmkCtMZSh1tzaGLq4hVnH
Heres the transaction I'd;
b5c534b623a643e6b2d1fdc5dd71d9f7d3dea40193039c08b85d97662615fdc0

**Comment by Bushstar** [comment]
The TX is there on the blockchain.

https://chainz.cryptoid.info/cann/address.dws?CQEJrMPdLkUYGcmkCtMZSh1tzaGLq4hVnH.htm

There are two wallets on the app store and the owner has no access to the old one so we have to create a new one listed here.

 https://play.google.com/store/apps/details?id=com.cannabiscoinfs420.wallet&hl=en_GB

Make sure you install the one above, if you have the wrong one export from the old one and try to import into this one.

**Comment by soulstar205** [comment]
I don't understand what it means by no wallet, does that mean there's no
particular wallet to my wallet id?
And how do we create a new one?

**Comment by Bushstar** [comment]
Where does it say "no wallet"?

**Comment by soulstar205** [comment]
At the website link you sent me, it says wallet: none.
I thought u were talking about the same thing when you said something about
a missing wallet.

**Comment by Bushstar** [comment]
Maybe we see a different view, on the Play Store, if you search for CannabisCoin Wallet one is by myself and the other by Altcoin Services, I'm wondering if you have the wrong one. Please double check and install the one made by Peter Bushnell if you do not have it. DO NOT uninstall your current wallet. You should be able to backup one wallet and import into the other one.

**Comment by soulstar205** [comment]
I downloaded the wallet from the link provided on the cannabis coin website
cannabiscoin.net
Do I still need to download another particular one?

**Comment by Bushstar** [comment]
There seems to be two linked from there, I presume that they are one and the same but will confirm with the owner. You may need to backup the wallet and extract the key with OpenSSL to import into a desktop wallet.

**Comment by soulstar205** [comment]
Could you give me a run through on how I'll back up the wallet and and
extract the key with OpenSSL to import into a desktop wallet.

**Comment by soulstar205** [comment]
I just realised something, I wasn't slidding to see the blocks downloaded
previously.
Now after I did, I'm Seeing dates on march 2016 on the blocks downloaded.
Does this I'm over a year behind in my wallet? And what do I do?

**Comment by Bushstar** [comment]
As long as the blockchain is updating then all you need to do is wait. To extract your private key from the backup you need to use OpenSSL with the following. The above message removed the filename bit because of the parenthesis it was copied with. You can install OpenSSL binaries from their website.

openssl enc -d -aes-256-cbc -a -in filename

**Comment by ghost** [comment]
I downloaded the Windows wallet and the Android wallet on my phone, both wallet are synchronizing for two days. I'm mining Cannabis Coin in multipool, they sent my rewards to the Android wallet but I only get hit and miss on the transactions. I'm missing more that 700 CANN coins. I think this project is dead.
